version: "3.9"

services:
  bot:
    build: .
    image: anonim:alpine
    container_name: anonim_con
    restart: always
    command: sh -c "python3 main.py"
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:3@pg:5432/postgres

  pg:
    image: postgres:alpine
    container_name: p27_pg_jaxongir
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3
      POSTGRES_DB: postgre
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alembic_container
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:3@pg:5432/postgres
    depends_on:
      - pg
    volumes:
      - .:/app
    command: ["alembic", "upgrade", "head"]

volumes:
  pgdata:
