version: "2.32.4"


services:
  bot:
    build: .
    image: anonim:alpine
    container_name: anonim_con
    restart: always
    command: sh -c "alembic revision --autogenerate -m 'Create a baseline migrations' &&
                    alembic upgrade head &&
                    python3 main.py"
    depends_on:
      - pg

  pg:
    image: postgres:alpine
    container_name: p27_pg_jaxongir
    restart: always
    environment:
      POSTGRES_PASSWORD: 3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: rd
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redisdata:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata:







